id: A3522A404
title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to the Glorious
  Guru Mahākāla Pañjaranātha'
type: translation
pechas:
- I3939346D
- I7F504F35
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:10:01.738376
  last_modified_at: 2023-01-04 12:10:01.738383
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I3939346D/A27A: 44D9
  I7F504F35/5440: 44D9
